name : Kichin
description : Kichin.
keyword : 
url : http://kichin.nyc
email : contact@kichin.nyc
analytics : UA-8418273-8
year : 2015
markdown : kramdown
exclude : [node_modules, scss/vendor.scss, bower_components, .vagrant]
host: 0.0.0.0
port: 4000
